### ISSUE TITLE
构建失败了

### ISSUE THREAD

**Issue by fengxiaojie** [Elegybackup/clash-backup#1]
go get -u -v github.com/Elegybackup/clash-backup
go: downloading github.com/Elegybackup/clash-backup v0.0.0-20231111124258-89fcd918fd87
go: downloading github.com/sirupsen/logrus v1.9.3
go: downloading golang.org/x/sys v0.0.0-20220715151400-c0bba94af5f8
go: downloading golang.org/x/sys v0.14.0
github.com/Elegybackup/clash-backup imports
        github.com/Dreamacro/clash/constant: cannot find module providing package github.com/Dreamacro/clash/constant
github.com/Elegybackup/clash-backup imports
        github.com/Dreamacro/clash/hub: cannot find module providing package github.com/Dreamacro/clash/hub
github.com/Elegybackup/clash-backup imports
        github.com/Dreamacro/clash/proxy/http: cannot find module providing package github.com/Dreamacro/clash/proxy/http
github.com/Elegybackup/clash-backup imports
        github.com/Dreamacro/clash/proxy/socks: cannot find module providing package github.com/Dreamacro/clash/proxy/socks
github.com/Elegybackup/clash-backup imports
        github.com/Dreamacro/clash/tunnel: cannot find module providing package github.com/Dreamacro/clash/tunnel

**Comment by Elegybackup** [comment]
github.com/Dreamacro/clash/proxy/http: cannot find module providing package github.com/Dreamacro/clash/proxy/这里的不是我的github仓库，而是原仓库，麻烦你改一下 即可编译

**Comment by kuisec** [comment]
> github.com/Dreamacro/clash/proxy/http: cannot find module providing package github.com/Dreamacro/clash/proxy/这里的不是我的github仓库，而是原仓库，麻烦你改一下 即可编译

如何更改呢？我并非Go语言开发者
